# TODO find a way to use stages with 2 parallel pipelines
#
# rationale: I'd like to have a 3 stages pipelines: install, test and deploy, and execute it for
# each supported node version.
#
# I cannot really do that now because gitlab does not seem to support having 2 distinct pipelines.
# the only thing you can do is:
#
#          stage install               stage test              stage deploy
# *---- npm i with node 8----*----npm test with node 8----*---...
#  \___ npm i with node 10__/ \___npm test with node 10___/
#
# this is problematic because I really don't want the node_modules/ folder to be mixed between
# versions.
#
# Instead, we'd like to have:
#
# *---- npm i with node 8----*----npm test with node 8----*---...
# *---- npm i with node 10---*----npm test with node 10___*---...
#

stages:
    - audit
    - build
    - lint
    - test
    - publish

default:
    image: node:lts-alpine
    interruptible: true
    tags:
        - saas-linux-large-amd64

variables:
    version_stable_release: '/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/'
    version_pre_release: '/^v[0-9]+\.[0-9]+\.[0-9]+\-(alpha|beta|rc)\.[0-9]+$/'

# Run pipelines on MR, tags and push on 'main'
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - node_modules/

check-commit-message:
    stage: lint
    script:
        - npm i
        - apk add --no-cache git
        - git fetch origin main
        - git remote set-head origin -a
        - npx commitlint -x @commitlint/config-conventional --from=origin/HEAD --to=${CI_COMMIT_SHA}

build_lts:
    stage: build
    script:
        - npm i
        - npm run make-package
    artifacts:
        paths:
            - build
            - giro3d-*.tgz
        name: "$CI_COMMIT_REF_SLUG"

build_current:
    stage: build
    image: node:current-alpine
    script:
        - export NODE_OPTIONS=--openssl-legacy-provider
        - npm i
        - npm run make-package

lint:
    stage: lint
    script:
        - npm i
        - npm run lint -- --max-warnings=0

audit:
    stage: audit
    script:
        - npm audit --omit=dev
    allow_failure: true

test_unit_lts:
    stage: test
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
    script:
        - npm i
        - npm run test-with-coverage
    artifacts:
        paths:
            - build

test_unit_current:
    stage: test
    coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
    image: node:current-alpine
    script:
        - npm i
        - npm run test-with-coverage

publish_prerelease_package:
    stage: publish
    interruptible: false
    retry: 1
    needs:
        - lint
        - test_unit_lts
        - build_lts
    script:
        - channel="$(echo "$CI_COMMIT_TAG" | sed -E 's/^v[0-9]+\.[0-9]+\.[0-9]+-([[:alnum:]]+)\.[0-9]+$/\1/')"
        - npm i
        - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        - npm run make-package
        - npm publish build/giro3d/ --access public --tag ${channel}
    rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $version_pre_release'

publish_package:
    stage: publish
    interruptible: false
    retry: 1
    needs:
        - lint
        - test_unit_lts
        - build_lts
    script:
        - npm i
        - npm config set -- '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        - npm run make-package
        - npm publish build/giro3d/ --access public
    rules:
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $version_stable_release'

pages:
    stage: publish
    needs:
        - publish_package
    script:
        - npm i
        - npm run build-site
        - mv build/site public
    artifacts:
        paths:
            - public
    rules:
        # Only publish website on releases (and exclude pre-releases)
        - if: '$CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $version_stable_release'
